/*
Copyright (c) 2014-2020 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module gscript.dynamic;

import std.conv;

enum Type
{
    Float,
    String,
    Array,
    Dictionary,
    Function,
    Reference,
    Null
}

struct Function
{
    ulong label;
    string name;
    uint numArguments;
}

struct Dynamic
{
    double asFloat = 0.0;
    string asString;
    Dynamic[] asArray;
    Dynamic[string] asDictionary;
    Dynamic* asRef;
    Function asFunction;

    Type type = Type.Null;

    this(double f)
    {
        asFloat = f;
        type = Type.Float;
    }

    this(double f, Type t)
    {
        asFloat = f;
        type = t;
    }

    this(string s)
    {
        asString = s;
        type = Type.String;
    }

    this(string s, Type t)
    {
        asString = s;
        type = t;
    }

    this(Type t)
    {
        type = t;
    }

    this(Function f)
    {
        asFunction = f;
        type = Type.Function;
    }

    this(Dynamic[] arr)
    {
        asArray = arr;
        type = Type.Array;
    }
    
    this(Dynamic[string] dict)
    {
        asDictionary = dict;
        type = Type.Dictionary;
    }

    this(Dynamic* r)
    {
        asRef = r;
        type = Type.Reference;
    }

    string toString()
    {
        if (type == Type.Float)
            return asFloat.to!string;
        else if (type == Type.String)
            return asString;
        else if (type == Type.Reference)
            return "@" ~ asRef.to!string;
        else if (type == Type.Array)
            return asArray.to!string;
        else if (type == Type.Function)
            return "Function";
         else if (type == Type.Dictionary)
            return asDictionary.to!string;
        else if (type == Type.Null)
            return "Null";
        else
            return "Dynamic(unknown)";
    }
}
