/*
Copyright (c) 2014-2024 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module gscript.gs;

import std.stdio;
import std.functional;
import std.path;

import gscript.parser;
import gscript.statement;
import gscript.vm;
import gscript.dynamic;
import gscript.program;
import gscript.stdhostfuncs;

/*
 * Script object represents a single GScript program,
 * with AST and IR code.
 * Once created, Script can be used and reused.
 * You can execute any local function from it
 * via GScript.executeFunction.
 */
class Script
{
    Module modul;
    alias modul this;

    string[] code;

    VirtualMachine vm;
}

/*
 * GScript is a factory object that compiles and links Scripts,
 * and executes functions from them.
 */
class GScript
{
   protected:
    Program prog;

   public:
    this()
    {
        prog = new Program();
        // 2.0 functions
        expose("assert", 1, &host_assert);
        expose("length", 1, &host_length);
        expose("array", -1, &host_array);
        expose("new", 1, &host_new);
        expose("writeln", -1, &host_writeln);
        expose("sqrt", 1, &host_sqrt);
        expose("pow", 2, &host_pow);
        expose("float", 1, &host_float);
        expose("sin", 1, &host_sin);
        expose("cos", 1, &host_cos);
        expose("typestr", 1, &host_typestr);
        expose("chcode", 1, &host_chcode);
        expose("format", -1, &host_format);
        
        // 2.1 functions
        expose("readText", 1, &host_readText);
    }

    void addImportDir(string dir)
    {
        prog.addImportDir(dir);
    }

    void expose(string name, int numArgs, Dynamic delegate(VirtualMachine, Dynamic[]) func)
    {
        prog.addHostFunction(name, numArgs, func);
    }

    void expose(string name, int numArgs, Dynamic function(VirtualMachine, Dynamic[]) func)
    {
        prog.addHostFunction(name, numArgs, toDelegate(func));
    }
    
    void setGlobal(string name, Dynamic value)
    {
        prog.global.asDictionary[name] = value;
    }

    Script loadScript(string text, string filename)
    {
        Script script = new Script();
        Parser parser = new Parser(prog, text, filename.extension, filename);
        script.modul = parser.moduleTree;
        script.code = generateCode(script);
        return script;
    }

    void executeFunction(string[] code, string name, Dynamic[] args = [])
    {
        if (code.length > 0)
        {
            auto vm = new VirtualMachine(code, prog);
            vm.runFunction(name, args);
        }
    }

   protected:

    string[] generateCode(Script s)
    {
        string[] res;
        res ~= "pass";
        res ~= "end";
        foreach(m; s.modul.imports)
            res ~= prog.modules[m.name].postfixCode();
        res ~= s.modul.postfixCode();
        return res;
    }
}

