/*
Copyright (c) 2014-2020 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module gscript.stack;

//enum maxStack = 64 * 1024;
class Stack(T, size_t maxStack = 64 * 1024)
{
    T[maxStack] data;
    long pointer;

    this()
    {
        pointer = -1;
    }
    void reset()
    {
        pointer = -1;
    }
    void push(T value)
    {
        pointer++;
        if (pointer==100) throw new Exception("Stack.push: stack overflow");
        data[pointer] = value;
    }
    T pop()
    {
        if (pointer==-1) throw new Exception("Stack.pop: stack underflow");
        T topval = data[pointer];
        pointer--;
        return topval;
    }
    T[] popArray(long len)
    {
        if (pointer==-1 || (pointer-len)<-1) throw new Exception("Stack.popArray: stack underflow");
        auto result = data[pointer-len+1..pointer+1];
        pointer = pointer-len;
        return result;
    }
    T[] popAll()
    {
        auto result = data[0..pointer+1];
        pointer = -1;
        return result;
    }
    T[] getAll()
    {
        return data[0..pointer+1];
    }
    T top()
    {
        if (pointer==-1) throw new Exception("Stack.top: stack underflow");
        return data[pointer];
    }
    long size()
    {
        return pointer+1;
    }
    bool empty()
    {
        return (pointer==-1);
    }
    long getPointer()
    {
        return pointer;
    }
    void setPointer(long sp)
    {
        pointer=sp;
        if (pointer>=100) throw new Exception("Stack.setPointer: stack overflow");
        else if (pointer<-1) throw new Exception("Stack.setPointer: stack underflow");
    }
    T getByPointer(long sp)
    {
        if (sp>=100) throw new Exception("Stack.getByPointer: stack overflow");
        else if (sp<0) throw new Exception("Stack.getByPointer: stack underflow");
        return data[sp];    
    }
    T* getPointerToElement(long sp)
    {
        if (sp>=100) throw new Exception("Stack.getPointerToElement: stack overflow");
        else if (sp<0) throw new Exception("Stack.getPointerToElement: stack underflow");
        return &(data[sp]);    
    }
    void setByPointer(long sp, T val)
    {
        if (sp>=100) throw new Exception("Stack.setByPointer: stack overflow");
        else if (sp<0) throw new Exception("Stack.setByPointer: stack underflow");
        data[sp] = val;    
    }
}

