/*
Copyright (c) 2020 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module main;

import std.stdio;
import std.file;
import std.path;
import std.conv;
import std.array;
import std.getopt;
import std.bitmanip;

import gscript.gs;
import gscript.dynamic;
import gscript.vm;

import std.process;

Dynamic hello(VirtualMachine vm, Dynamic[] args)
{
    writeln("Hello!");
    return Dynamic(0);
}

void saveIR(string[] code, string filename)
{
    File file = File(filename, "w");
    foreach(instr; code)
    {
        file.write(instr ~ '\0');
    }
}

string[] loadIR(string filename)
{
    string blob = readText(filename);
    return blob.split("\0");
}

string[] compileScript(GScript gs, string filename)
{
    string text = readText(filename);
    auto script = gs.loadScript(text, filename);
    return script.code;
}

void main(string[] args)
{
    GScript gs = new GScript();
    gs.expose("hello", 0, &hello);

    string exeFilename = args[0];

    bool ir = false;
    string outputFilename = "";
    
    string filename = "";
    string altFilename1 = "main.gs";
    string altFilename2 = "main.ir";
    
    string targetName;

    getopt(args, 
        std.getopt.config.passThrough,
        std.getopt.config.caseSensitive,
        "output", &outputFilename,
        "ir", &ir);
    
    if (args.length > 1)
    {
        filename = args[1];
    }
    
    string[] code;
    
    if (filename.length)
    {
        targetName = filename.stripExtension;
        
        if (exists(filename)) 
        {
            if (filename.extension == ".ir")
                code = loadIR(filename);
            else
                code = gs.compileScript(filename);
        }
        else
        {
            writeln("Cannot find \"" ~ filename ~ "\"");
            return;
        }
    }
    else
    {
        if (exists(altFilename1)) 
        {
            targetName = altFilename1.stripExtension;
            code = gs.compileScript(altFilename1);
        }
        else if (exists(altFilename2)) 
        {
            targetName = altFilename2.stripExtension;
            code = loadIR(altFilename2);
        }
        else
        {
            writeln("Cannot find \"" ~ altFilename1 ~ "\" of \"" ~ altFilename2 ~ "\", please specify a file to run");
            return;
        }
    }

    if (ir)
    {
        if (outputFilename == "")
            outputFilename = targetName ~ ".ir";
        saveIR(code, outputFilename);
    }
    else
    {
        Dynamic gsArgs = Dynamic(Type.Array);
        if (args.length > 2)
            foreach(a; args[2..$])
                gsArgs.asArray ~= Dynamic(a);

        gs.executeFunction(code, "main", [gsArgs]);
    }
}
